
default: &default
  adapter: postgresql

development:
  adapter: sqlite3
  database: db/master.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: d57lig22csj52u
  username: trbwoydahfqqxc
  host: ec2-34-200-205-45.compute-1.amazonaws.com
  password: 076e0bc0b21babc822b730567673e8e484dfe4dc15d3e120f75bd2121037bc14
